### ISSUE TITLE
Is there any way to improve the accuracy of the mlx90614?

### ISSUE THREAD

**Issue by jhysum** [balassy/laser-temp-gun#2]
Hi,

This isn't an issue for the temp gun repo but I was wondering if there is any way for you to improve the accuracy beyond .5C? 

If you have any advice for this, I'll love to hear about it.

**Comment by balassy** [comment]
The 0.5 C accuracy is the official nominal value of the sensor, and I don't know any way to improve it. I ordered my sensor from AliExpress and this particular cheap device is way more off than 0.5 C :(
